const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const{createPrepaidOrder,configured}=require('./shiprocket-service');require('dotenv').config();
const publicPort=Number(process.env.PORT||3000);let ordersPort=Number(process.env.SHIPROCKET_ORDERS_GATEWAY_PORT||3301);const storePort=Number(process.env.ROYALWRAP_INTERNAL_PORT||3101);if(ordersPort===publicPort)ordersPort+=1;const dataDir=path.join(__dirname,'data');const pendingFile=path.join(dataDir,'pending-shiprocket-orders.json');const shipmentsFile=path.join(dataDir,'shiprocket-orders.json');const adminKey=String(process.env.ADMIN_KEY||'');fs.mkdirSync(dataDir,{recursive:true});
function safe(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}function admin(req){return adminKey.length>=8&&safe(req.headers['x-admin-key'],adminKey)}function send(res,status,payload){const body=JSON.stringify(payload);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'});res.end(body)}function read(file,fallback){try{return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):fallback}catch{return fallback}}function write(file,value){const tmp=`${file}.tmp`;fs.writeFileSync(tmp,JSON.stringify(value,null,2));fs.renameSync(tmp,file)}
function body(req,limit=262144){return new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',c=>{size+=c.length;if(size>limit){reject(Object.assign(new Error('Request body is too large.'),{statusCode:413}));req.destroy();return}chunks.push(c)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)})}function json(buffer){if(!buffer.length)return{};try{return JSON.parse(buffer.toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON body.'),{statusCode:400})}}
function proxyBuffered(req,buffer){return new Promise((resolve,reject)=>{const headers={...req.headers,host:`127.0.0.1:${ordersPort}`};delete headers['transfer-encoding'];headers['content-length']=Buffer.byteLength(buffer);const p=http.request({hostname:'127.0.0.1',port:ordersPort,path:req.url,method:req.method,headers},r=>{const chunks=[];r.on('data',c=>chunks.push(c));r.on('end',()=>resolve({status:r.statusCode||502,headers:r.headers,body:Buffer.concat(chunks)}))});p.on('error',reject);if(buffer.length)p.write(buffer);p.end()})}
function proxy(req,res){const p=http.request({hostname:'127.0.0.1',port:ordersPort,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${ordersPort}`}},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res)});p.on('error',e=>!res.headersSent?send(res,502,{error:`Store is unavailable: ${e.message}`}):res.end());req.pipe(p)}
function savePending(order,request){const all=read(pendingFile,{});all[order.orderId]={razorpayOrderId:order.orderId,receipt:order.receipt,customer:request.customer||{},items:order.items||[],amount:order.displayAmount,currency:order.currency||'INR',createdAt:new Date().toISOString()};write(pendingFile,all)}
async function sync(orderId,paymentId){const shipments=read(shipmentsFile,{}),existing=shipments[orderId];if(existing?.shiprocketOrderId||existing?.shipmentId)return existing;const pending=read(pendingFile,{})[orderId];if(!pending)throw new Error('Paid order details were not found for Shiprocket sync.');const now=new Date().toISOString();if(!configured()){const record={razorpayOrderId:orderId,receipt:pending.receipt,paymentId,syncStatus:'not_configured',error:'Add Shiprocket API credentials and pickup location in Render.',updatedAt:now};shipments[orderId]=record;write(shipmentsFile,shipments);return record}try{const response=await createPrepaidOrder({...pending,paymentId,paidAt:now});const record={razorpayOrderId:orderId,receipt:pending.receipt,paymentId,syncStatus:'created',shiprocketOrderId:response.order_id||response.orderId||'',shipmentId:response.shipment_id||response.shipmentId||'',awbCode:response.awb_code||'',courierName:response.courier_name||'',shiprocketStatus:response.status||'NEW',statusCode:response.status_code??null,response,updatedAt:new Date().toISOString()};shipments[orderId]=record;write(shipmentsFile,shipments);return record}catch(e){const record={razorpayOrderId:orderId,receipt:pending.receipt,paymentId,syncStatus:'failed',error:e.message||'Shiprocket order creation failed.',updatedAt:new Date().toISOString()};shipments[orderId]=record;write(shipmentsFile,shipments);return record}}
async function createOrder(req,res){const buffer=await body(req),request=json(buffer),result=await proxyBuffered(req,buffer);if(result.status>=200&&result.status<300){try{const data=JSON.parse(result.body.toString('utf8'));if(data.orderId)savePending(data,request)}catch(e){console.error('Shiprocket pending order save failed:',e.message)}}res.writeHead(result.status,result.headers);res.end(result.body)}
async function verify(req,res){const buffer=await body(req),request=json(buffer),result=await proxyBuffered(req,buffer);let data={};try{data=JSON.parse(result.body.toString('utf8'))}catch{}if(result.status>=200&&result.status<300&&data.success){const orderId=data.orderId||request.razorpay_order_id,paymentId=data.paymentId||request.razorpay_payment_id;data.shiprocket=await sync(orderId,paymentId);return send(res,result.status,data)}res.writeHead(result.status,result.headers);res.end(result.body)}
async function shiprocketAdmin(req,res,url){if(!admin(req))return send(res,401,{error:'Invalid admin key.'});if(req.method==='GET'&&url.pathname==='/api/admin/shiprocket/orders')return send(res,200,{shipments:Object.values(read(shipmentsFile,{}))});const match=url.pathname.match(/^\/api\/admin\/shiprocket\/orders\/([^/]+)\/retry$/);if(req.method==='POST'&&match){const id=decodeURIComponent(match[1]),current=read(shipmentsFile,{})[id]||{};const shipment=await sync(id,current.paymentId||'');return send(res,200,{success:shipment.syncStatus==='created',shipment})}return send(res,404,{error:'Shiprocket admin route not found.'})}
process.env.PORT=String(ordersPort);process.env.ROYALWRAP_INTERNAL_PORT=String(storePort);require('./orders-gateway');process.env.PORT=String(publicPort);
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/admin/shiprocket/'))return await shiprocketAdmin(req,res,url);if(req.method==='POST'&&url.pathname==='/api/create-order')return await createOrder(req,res);if(req.method==='POST'&&url.pathname==='/api/verify-payment')return await verify(req,res);return proxy(req,res)}catch(e){return send(res,e.statusCode||500,{error:e.message||'Shiprocket integration failed.'})}}).listen(publicPort,()=>console.log(`RoyalWrap Shiprocket gateway running at http://localhost:${publicPort}`));
