const https=require('https');
let tokenCache={token:'',expiresAt:0};
const HOST='apiv2.shiprocket.in';

function configured(){return Boolean(process.env.SHIPROCKET_EMAIL&&process.env.SHIPROCKET_PASSWORD&&process.env.SHIPROCKET_PICKUP_LOCATION);}
function num(name,fallback){const n=Number(process.env[name]);return Number.isFinite(n)&&n>0?n:fallback;}
function api(method,path,payload,token){const body=payload===undefined?'':JSON.stringify(payload);return new Promise((resolve,reject)=>{const req=https.request({hostname:HOST,port:443,path,method,headers:{Accept:'application/json','Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(body?{'Content-Length':Buffer.byteLength(body)}:{})},timeout:20000},res=>{let text='';res.setEncoding('utf8');res.on('data',c=>text+=c);res.on('end',()=>{let data={};try{data=text?JSON.parse(text):{};}catch{data={raw:text};}if(res.statusCode<200||res.statusCode>=300){const err=new Error(String(data.message||data.error||`Shiprocket API returned HTTP ${res.statusCode}.`));err.statusCode=res.statusCode||502;return reject(err);}resolve(data);});});req.on('timeout',()=>req.destroy(new Error('Shiprocket API request timed out.')));req.on('error',reject);if(body)req.write(body);req.end();});}
async function token(force=false){if(!configured()){const e=new Error('Shiprocket credentials or pickup location are not configured.');e.code='SHIPROCKET_NOT_CONFIGURED';throw e;}if(!force&&tokenCache.token&&Date.now()<tokenCache.expiresAt)return tokenCache.token;const result=await api('POST','/v1/external/auth/login',{email:process.env.SHIPROCKET_EMAIL,password:process.env.SHIPROCKET_PASSWORD});if(!result.token)throw new Error('Shiprocket did not return an API token.');tokenCache={token:result.token,expiresAt:Date.now()+8*60*60*1000};return tokenCache.token;}
async function authed(method,path,payload){let t=await token();try{return await api(method,path,payload,t);}catch(e){if(e.statusCode!==401)throw e;t=await token(true);return api(method,path,payload,t);}}
function splitName(value){const p=String(value||'').trim().split(/\s+/).filter(Boolean);return{first:p.shift()||'Customer',last:p.join(' ')}};
function orderDate(value){const d=value?new Date(value):new Date();const p=v=>String(v).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;}
function sku(item){return[item.id,item.brand,item.model].filter(Boolean).join('-').replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,80);}
async function createPrepaidOrder(order){const customer=order.customer||{};const items=Array.isArray(order.items)?order.items:[];if(!customer.city||!customer.state)throw new Error('Customer city and state are required for Shiprocket.');if(!items.length)throw new Error('Shiprocket order cannot be created without products.');const name=splitName(customer.name);return authed('POST','/v1/external/orders/create/adhoc',{order_id:String(order.receipt||order.razorpayOrderId),order_date:orderDate(order.paidAt||order.createdAt),pickup_location:process.env.SHIPROCKET_PICKUP_LOCATION,channel_id:'',comment:`RoyalWrap prepaid. Razorpay: ${order.paymentId||''}`.slice(0,200),billing_customer_name:name.first,billing_last_name:name.last,billing_address:String(customer.address||'').slice(0,180),billing_address_2:'',billing_city:String(customer.city).slice(0,80),billing_pincode:String(customer.pincode||''),billing_state:String(customer.state).slice(0,80),billing_country:'India',billing_email:String(customer.email||''),billing_phone:String(customer.mobile||''),shipping_is_billing:true,order_items:items.map(i=>({name:`${i.name} - ${i.brand} ${i.model}`.slice(0,120),sku:sku(i),units:Number(i.qty||1),selling_price:Number(i.unitPrice||0),discount:'',tax:'',hsn:''})),payment_method:'Prepaid',shipping_charges:0,giftwrap_charges:0,transaction_charges:0,total_discount:0,sub_total:Number(order.amount||0),length:num('SHIPROCKET_PACKAGE_LENGTH_CM',15),breadth:num('SHIPROCKET_PACKAGE_BREADTH_CM',10),height:num('SHIPROCKET_PACKAGE_HEIGHT_CM',1),weight:num('SHIPROCKET_PACKAGE_WEIGHT_KG',0.25)});}
module.exports={createPrepaidOrder,configured};
